package org.softala.roboapp.model.helpModels;

import java.io.Serializable;

/**
 * @author Team1 - Petri Kortelainen
 * Bean for receiving singular answers from the frontend
 * and saving to the database
 */
public class AnswerHandlerBean implements Serializable{
	String answer_option_id; //id of selected answer
	String session_id;	//session id generated by DB
	String textfieldAnswer; //in case we need to collect an answer from text field to backend
	
	/**
	 * @return id of the selected answer option
	 */
	public String getAnswer_option_id() {
		return answer_option_id;
	}
	
	/**
	 * @param answer_option_id id of the selected answer option 
	 */
	public void setAnswer_option_id(String answer_option_id) {
		this.answer_option_id = answer_option_id;
	}
	
	/**
	 * @return the user session id related to the answer
	 */
	public String getSession_id() {
		return session_id;
	}
	
	/**
	 * @param session_id the user session id to set for the answer
	 */
	public void setSession_id(String session_id) {
		this.session_id = session_id;
	}
	
	/**
	 * @return answer text field contents
	 */
	public String getTextfieldAnswer() {
		return textfieldAnswer;
	}
	
	/**
	 * @param textfieldAnswer answer text field contents
	 */
	public void setTextfieldAnswer(String textfieldAnswer) {
		this.textfieldAnswer = textfieldAnswer;
	}
	
	/**
	 * Bean constructor with parameters
	 * @param answer_option_id id of the selected answer option
	 * @param session_id id of the user session
	 * @param textfieldAnswer answer text field
	 */
	public AnswerHandlerBean(String answer_option_id, String session_id,
			String textfieldAnswer) {
		this.answer_option_id = answer_option_id;
		this.session_id = session_id;
		this.textfieldAnswer = textfieldAnswer;
	}
	
	/**
	 * Empty bean constructor
	 */
	public AnswerHandlerBean() {
		this.answer_option_id = "";
		this.session_id = "";
		this.textfieldAnswer = "";
	}
}