package org.softala.roboapp.model;
// default package
// Generated Sep 28, 2015 12:35:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnswerOptionId generated by hbm2java
 */
@Embeddable
public class AnswerOptionId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1962052299832232682L;
	
	private String answerOptionId;
	private String questionId;
	private int dialogId;

	public AnswerOptionId() {
	}

	public AnswerOptionId(String answerOptionId, String questionId, int dialogId) {
		this.answerOptionId = answerOptionId;
		this.questionId = questionId;
		this.dialogId = dialogId;
	}

	@Column(name = "answer_option_id", nullable = false, length = 50)
	public String getAnswerOptionId() {
		return this.answerOptionId;
	}

	public void setAnswerOptionId(String answerOptionId) {
		this.answerOptionId = answerOptionId;
	}

	@Column(name = "question_id", nullable = false, length = 10)
	public String getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(String questionId) {
		this.questionId = questionId;
	}

	@Column(name = "dialog_id", nullable = false)
	public int getDialogId() {
		return this.dialogId;
	}

	public void setDialogId(int dialogId) {
		this.dialogId = dialogId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AnswerOptionId))
			return false;
		AnswerOptionId castOther = (AnswerOptionId) other;

		return ((this.getAnswerOptionId() == castOther.getAnswerOptionId()) || (this
				.getAnswerOptionId() != null
				&& castOther.getAnswerOptionId() != null && this
				.getAnswerOptionId().equals(castOther.getAnswerOptionId())))
				&& ((this.getQuestionId() == castOther.getQuestionId()) || (this
						.getQuestionId() != null
						&& castOther.getQuestionId() != null && this
						.getQuestionId().equals(castOther.getQuestionId())))
				&& (this.getDialogId() == castOther.getDialogId());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getAnswerOptionId() == null ? 0 : this.getAnswerOptionId()
						.hashCode());
		result = 37
				* result
				+ (getQuestionId() == null ? 0 : this.getQuestionId()
						.hashCode());
		result = 37 * result + this.getDialogId();
		return result;
	}

}
