package org.softala.roboapp.model;
// default package
// Generated Oct 26, 2015 8:47:24 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2015 Haaga-Helia ammattikorkeakoulu Oy ab
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * 
 * Closing generated by hbm2java
 * 
 * Entity mapped to the closing table in the database
 */
@Entity
@Table(name = "Closing")
public class Closing implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7713748499593318532L;
	private Integer closingId;
	private String text;
	private String productUrl;
	private String toEmail;
	private Set<AnswerOption> answerOptions = new HashSet<AnswerOption>();

	public Closing() {
	}

	public Closing(String text) {
		this.text = text;
	}

	public Closing(String text, String productUrl, String toEmail,
			Set<AnswerOption> answerOptions) {
		this.text = text;
		this.productUrl = productUrl;
		this.toEmail = toEmail;
		this.answerOptions = answerOptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "closing_id", unique = true, nullable = false)
	public Integer getClosingId() {
		return this.closingId;
	}

	public void setClosingId(Integer closingId) {
		this.closingId = closingId;
	}

	@Column(name = "text", nullable = false, length = 2000)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "product_url", length = 2083)
	public String getProductUrl() {
		return this.productUrl;
	}

	public void setProductUrl(String productUrl) {
		this.productUrl = productUrl;
	}

	@Column(name = "to_email", length = 254)
	public String getToEmail() {
		return this.toEmail;
	}

	public void setToEmail(String toEmail) {
		this.toEmail = toEmail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "closing")
	@JsonBackReference
	public Set<AnswerOption> getAnswerOptions() {
		return this.answerOptions;
	}

	public void setAnswerOptions(Set<AnswerOption> answerOptions) {
		this.answerOptions = answerOptions;
	}

}
