package org.softala.roboapp.model;
// default package
// Generated Oct 26, 2015 8:47:24 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2015 Haaga-Helia ammattikorkeakoulu Oy ab
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * 
 * GivenAnswerId generated by hbm2java
 * 
 * ID object from the composite key in given_answer table
 * for use in the GivenAnswer object
 */
@Embeddable
public class GivenAnswerId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -916280044465975402L;
	private String sessionId;
	private int answerOptionId;

	public GivenAnswerId() {
	}

	public GivenAnswerId(String sessionId, int answerOptionId) {
		this.sessionId = sessionId;
		this.answerOptionId = answerOptionId;
	}

	@Column(name = "session_id", nullable = false, length = 128)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "answer_option_id", nullable = false)
	public int getAnswerOptionId() {
		return this.answerOptionId;
	}

	public void setAnswerOptionId(int answerOptionId) {
		this.answerOptionId = answerOptionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GivenAnswerId))
			return false;
		GivenAnswerId castOther = (GivenAnswerId) other;

		return ((this.getSessionId() == castOther.getSessionId()) || (this
				.getSessionId() != null && castOther.getSessionId() != null && this
				.getSessionId().equals(castOther.getSessionId())))
				&& (this.getAnswerOptionId() == castOther.getAnswerOptionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSessionId() == null ? 0 : this.getSessionId().hashCode());
		result = 37 * result + this.getAnswerOptionId();
		return result;
	}

}
