package org.softala.roboapp.model;
// default package
// Generated Sep 28, 2015 12:35:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * GivenAnswer generated by hbm2java
 */
@Entity
@Table(name = "GivenAnswer")
public class GivenAnswer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4262538939830037083L;
	
	private GivenAnswerId id;
	private AnswerOption answerOption;
	private Session session;
	private Date created;

	public GivenAnswer() {
	}

	public GivenAnswer(GivenAnswerId id, AnswerOption answerOption,
			Session session, Date created) {
		this.id = id;
		this.answerOption = answerOption;
		this.session = session;
		this.created = created;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "sessionId", column = @Column(name = "session_id", nullable = false, length = 50)),
			@AttributeOverride(name = "answerOptionId", column = @Column(name = "answer_option_id", nullable = false, length = 50)),
			@AttributeOverride(name = "questionId", column = @Column(name = "question_id", nullable = false, length = 10)),
			@AttributeOverride(name = "dialogId", column = @Column(name = "dialog_id", nullable = false)) })
	public GivenAnswerId getId() {
		return this.id;
	}

	public void setId(GivenAnswerId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "answer_option_id", referencedColumnName = "answer_option_id", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "question_id", referencedColumnName = "question_id", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "dialog_id", referencedColumnName = "dialog_id", nullable = false, insertable = false, updatable = false) })
	@JsonBackReference
	public AnswerOption getAnswerOption() {
		return this.answerOption;
	}

	public void setAnswerOption(AnswerOption answerOption) {
		this.answerOption = answerOption;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "session_id", nullable = false, insertable = false, updatable = false)
	@JsonBackReference
	public Session getSession() {
		return this.session;
	}

	public void setSession(Session session) {
		this.session = session;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
