package org.softala.roboapp.model;
// default package
// Generated Sep 28, 2015 12:35:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuestionId generated by hbm2java
 */
@Embeddable
public class QuestionId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6985076052668193922L;
	
	private String questionId;
	private int dialogId;

	public QuestionId() {
	}

	public QuestionId(String questionId, int dialogId) {
		this.questionId = questionId;
		this.dialogId = dialogId;
	}

	@Column(name = "question_id", nullable = false, length = 10)
	public String getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(String questionId) {
		this.questionId = questionId;
	}

	@Column(name = "dialog_id", nullable = false)
	public int getDialogId() {
		return this.dialogId;
	}

	public void setDialogId(int dialogId) {
		this.dialogId = dialogId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QuestionId))
			return false;
		QuestionId castOther = (QuestionId) other;

		return ((this.getQuestionId() == castOther.getQuestionId()) || (this
				.getQuestionId() != null && castOther.getQuestionId() != null && this
				.getQuestionId().equals(castOther.getQuestionId())))
				&& (this.getDialogId() == castOther.getDialogId());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getQuestionId() == null ? 0 : this.getQuestionId()
						.hashCode());
		result = 37 * result + this.getDialogId();
		return result;
	}

}
