package org.softala.roboapp.model;
// default package
// Generated Sep 28, 2015 12:35:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "Question")
public class Question implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1881288301979497581L;
	
	private QuestionId id;
	private Dialog dialog;
	private String text;
	private String answerType;
	private Set<AnswerOption> answerOptions = new HashSet<AnswerOption>(0);

	public Question() {
	}

	public Question(QuestionId id, Dialog dialog, String text, String answerType) {
		this.id = id;
		this.dialog = dialog;
		this.text = text;
		this.answerType = answerType;
	}

	public Question(QuestionId id, Dialog dialog, String text,
			String answerType, Set<AnswerOption> answerOptions) {
		this.id = id;
		this.dialog = dialog;
		this.text = text;
		this.answerType = answerType;
		this.answerOptions = answerOptions;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "questionId", column = @Column(name = "question_id", nullable = false, length = 10)),
			@AttributeOverride(name = "dialogId", column = @Column(name = "dialog_id", nullable = false)) })
	public QuestionId getId() {
		return this.id;
	}

	public void setId(QuestionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dialog_id", nullable = false, insertable = false, updatable = false)
	@JsonBackReference
	public Dialog getDialog() {
		return this.dialog;
	}

	public void setDialog(Dialog dialog) {
		this.dialog = dialog;
	}

	@Column(name = "text", nullable = false, length = 1000)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "answer_type", nullable = false, length = 50)
	public String getAnswerType() {
		return this.answerType;
	}

	public void setAnswerType(String answerType) {
		this.answerType = answerType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	@JsonManagedReference
	public Set<AnswerOption> getAnswerOptions() {
		return this.answerOptions;
	}

	public void setAnswerOptions(Set<AnswerOption> answerOptions) {
		this.answerOptions = answerOptions;
	}

}
