package org.softala.roboapp.model;
// default package
// Generated Sep 28, 2015 12:35:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name = "Session")
public class Session implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7180735118846455219L;
	
	private String sessionId;
	private String userType;
	private Date created;
	private Set<GivenAnswer> givenAnswers = new HashSet<GivenAnswer>(0);

	public Session() {
	}

	public Session(String sessionId, Date created) {
		this.sessionId = sessionId;
		this.created = created;
	}

	public Session(String sessionId, String userType, Date created,
			Set<GivenAnswer> givenAnswers) {
		this.sessionId = sessionId;
		this.userType = userType;
		this.created = created;
		this.givenAnswers = givenAnswers;
	}

	@Id
	@Column(name = "session_id", unique = true, nullable = false, length = 50)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "user_type", length = 20)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "session")
	@JsonManagedReference
	public Set<GivenAnswer> getGivenAnswers() {
		return this.givenAnswers;
	}

	public void setGivenAnswers(Set<GivenAnswer> givenAnswers) {
		this.givenAnswers = givenAnswers;
	}

}
