package org.softala.roboapp.controller;

import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import org.softala.roboapp.model.AnswerOption;
import org.softala.roboapp.model.Dialog;
import org.softala.roboapp.model.GivenAnswer;
import org.softala.roboapp.model.GivenAnswerId;
import org.softala.roboapp.model.Question;
import org.softala.roboapp.model.Session;
import org.softala.roboapp.model.helpModels.AnswerHandlerBean;
import org.softala.roboapp.model.helpModels.AnswerLevelPerAnswer;
import org.softala.roboapp.repository.DialogRepository;
import org.softala.roboapp.repository.GivenAnswerRepository;
import org.softala.roboapp.repository.SessionRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

/**
 * 
 * @author team 1 - Petri Kortelainen
 *
 */

/*
 * TODO commentoi toiminta Generoi Sesson ID, Tallenna kantaan vastauksia
 */

@RestController
@RequestMapping("/Front")
// "FrontTEST" for now but later well change it to "/" - when so remove this
// comment
public class FrontendController {

	@Autowired
	private GivenAnswerRepository GivAnswRepository;

	@Autowired
	private SessionRepository sessionRepository;

	@Autowired
	private DialogRepository dialogrepository;

	public Session newSession() {
		// TODO Maybe not executed here WIP
		// session generator
		Session session = new Session();
		Date date = new Date();

		// generating an id from current time
		long cTM;
		String genID = "";
		int hash;

		do {
			try {
				// id generated by making hashmap out of millisecond timer value
				cTM = System.currentTimeMillis();
				hash = (int) cTM;
				genID = "" + hash;
				genID = FrontendController.this.hashString(genID);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			// if id already exists which is very unlikely another id is made
			// if need be 1 can add random gen number to the hash gen value to
			// make it even more unique but that isn't necessary
		} while (genID == null || sessionRepository.exists(genID));
		session.setSessionId(genID);
		session.setCreated(date);

		// sessio tallenetaan muualla atm
		sessionRepository.save(session);
		return session;
	}

	@RequestMapping(value = "/postClick", method = RequestMethod.POST)
	/**
	 * On each click frontend sends post here which is saved into database
	 * @param AHB
	 * @return
	 */
	public @ResponseBody HashMap<String, String> saveClick(
			@RequestBody AnswerHandlerBean AHB) {

		/*
		 * AHB is a bean that contains information on a single click receive a
		 * single answer from front end and post it to server login coming data
		 * must reflect the model in question {"answer_option_id": "int",
		 * "session_id":"String", "textfieldAnswer":"String"}
		 * 
		 * Textfield is for latter use in case we ever want to use input instead
		 * of choice. Beans from frontend are to be handled with converter but
		 * for now AHB is RAW for now
		 */

		Session session = new Session();
		String testId = "";

		// Map for response
		HashMap<String, String> resMap = new HashMap<String, String>();

		try {
			testId = AHB.getSession_id();
		} catch (Exception e) {
			e.printStackTrace();
		}

		// testataan joskus tässä onko olemassa id annettuna
		if (testId != null && testId != "") {
			// TIME TO CHECK SESSION ID
			if (sessionRepository.exists(testId)) {
				session.setSessionId(testId);
			} else {
				// given session id is fake
				resMap.put("WARNING:", "FAKE SESSION ID GIVEN");
				return resMap;
			}
		} else {
			// NEW SESSION GENERATOR
			session = FrontendController.this.newSession();
			testId = session.getSessionId();
		}

		GivenAnswer ga = new GivenAnswer();
		AnswerOption ao = new AnswerOption();
		GivenAnswerId gai = new GivenAnswerId();

		// GivenAnswerId content
		gai.setSessionId(testId);
		String aoID = AHB.getAnswer_option_id();
		int foo = 0;
		try {
			foo = Integer.parseInt(aoID);
		} catch (NumberFormatException e) {
			System.out.println("parse to int kusi, aoID:" + aoID);
			e.printStackTrace();
		}
		gai.setAnswerOptionId(foo);

		// AnswerOption content
		ao.setAnswerOptionId(foo);

		// GivenAnswer content
		ga.setId(gai);
		ga.setCreated(new Date());
		ga.setSession(session);
		ga.setAnswerOption(ao);

		GivAnswRepository.save(ga);
		resMap.put("session_id", testId);
		return resMap;
	}

	@RequestMapping("/getTree")
	/**
	 * Give tree to backend
	 * @return
	 */
	public Iterable getTree() {

		// TODO handle multiple threes so that only 1 is given to frontend based
		// on number of activated threes

		ArrayList<Dialog> d = new ArrayList<Dialog>();
		ArrayList<Integer> a = null;
		try {
			a = dialogrepository.findEnabled();
			for (int i = 0; i < a.size(); i++) {
				d.add(dialogrepository.findOne(a.get(i)));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

		return d;
	}

	/**
	 * hash map generator
	 * 
	 * @param s
	 * @return
	 * @throws NoSuchAlgorithmException
	 */
	public String hashString(String s) throws NoSuchAlgorithmException {
		byte[] hash = null;
		try {
			MessageDigest md = MessageDigest.getInstance("SHA-256");
			hash = md.digest(s.getBytes());

		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		}
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < hash.length; ++i) {
			String hex = Integer.toHexString(hash[i]);
			if (hex.length() == 1) {
				sb.append(0);
				sb.append(hex.charAt(hex.length() - 1));
			} else {
				sb.append(hex.substring(hex.length() - 2));
			}
		}
		return sb.toString();
	}

}
